spring:
  application:
    name: grabeat-backend

  config:
    import:
      - optional:application-database.yml
      - optional:application-jwt.yml
      - optional:application-mail.yml
      - optional:application-khalti.yml

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8081

app:
  upload-dir: uploads/images

logging:
  level:
    org.springframework.security: DEBUG
    com.nischal.backend: DEBUG
